server:
  port: 8845
spring:
  application:
    name: @artifactId@ #拿到POM文件中的值
  profiles:
    active: @facility@
  cloud:
    circuitbreaker:
      sentinel:
        enabled: false
  security:
    oauth2:
      client:
        registration:
          dante-cloud:
            provider: dante-cloud
            client-id: 0ca42420efae46da91e51ee5cd8f27ad
            client-secret: 2a6280e17b6e43fb8e9c681f21630f19
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "http://192.168.101.10:8847/dante-cloud-monitor/login/oauth2/code/{registrationId}"
        provider:
          dante-cloud:
            issuer-uri: http://192.168.101.10:8847/dante-cloud-uaa
            authorization-uri: http://192.168.101.10:8847/dante-cloud-uaa/oauth2/authorize
            token-uri: http://192.168.101.10:8847/dante-cloud-uaa/oauth2/token

---
# spring cloud alibaba 基础设施配置
spring:
  config:
    activate:
      on-profile: alibaba
  cloud:
    nacos:
      username: ${ALIBABA_USERNAME:@alibaba.username@}
      password: ${ALIBABA_PASSWORD:@alibaba.password@}
      config:
        namespace: ${ALIBABA_NAMESPACE:@alibaba.namespace@}
        server-addr: ${ALIBABA_CONFIG_SERVER_ADDR:@alibaba.config.server-addr@}
        file-extension: yaml
        import-check:
          enabled: false
      discovery:
        namespace: ${ALIBABA_NAMESPACE:@alibaba.namespace@}
        server-addr: ${ALIBABA_DISCOVERY_SERVER_ADDR:@alibaba.discovery.server-addr@}
    httpclientfactories:
      ok:
        enabled: false

---
# spring cloud tencent 基础设施配置
spring:
  config:
    activate:
      on-profile: tencent
  cloud:
#    inetutils:
#      ignored-interfaces:
#        - eth0
    polaris:
      enabled: true
      address: ${TENCENT_POLARIS_SERVER_ADDR:grpc://@tencent.polaris.server-addr@}
      namespace: ${TENCENT_POLARIS_NAMESPACE:@tencent.polaris.namespace@}
      discovery:
        heartbeat-interval: 30
---
# spring 全家桶基础设施配置
spring:
  config:
    activate:
      on-profile: spring
  cloud:
    inetutils:
      ignored-interfaces:
        - eth0
    zookeeper:
      discovery:
        instance-host: ${spring.cloud.client.ip-address}