herodotus:
  endpoint:
    uaa-service-name: dante-cloud-uaa
    upms-service-name: dante-cloud-upms
    message-service-name: dante-cloud-message
    oss-service-name: dante-cloud-oss-ability
    gateway-service-uri: ${herodotus.environment.gateway-server-addr}
    uaa-service-uri: ${herodotus.endpoint.gateway-service-uri}/${herodotus.endpoint.uaa-service-name}
    upms-service-uri: ${herodotus.endpoint.gateway-service-uri}/${herodotus.endpoint.upms-service-name}
    message-service-uri: ${herodotus.endpoint.gateway-service-uri}/${herodotus.endpoint.message-service-name}
    oss-service-uri: ${herodotus.endpoint.gateway-service-uri}/${herodotus.endpoint.oss-service-name}
    access-token-uri: ${herodotus.endpoint.uaa-service-uri}/oauth2/token
    authorization-uri: ${herodotus.endpoint.uaa-service-uri}/oauth2/authorize
    pushed-authorization-request-uri: ${herodotus.endpoint.uaa-service-uri}/oauth2/par
    token-revocation-uri: ${herodotus.endpoint.uaa-service-uri}/oauth2/revoke
    token-introspection-uri: ${herodotus.endpoint.uaa-service-uri}/oauth2/introspect
    jwk-set-uri: ${herodotus.endpoint.uaa-service-uri}/oauth2/jwks
    issuer-uri: ${herodotus.endpoint.uaa-service-uri}
    oidc-client-registration-uri: ${herodotus.endpoint.uaa-service-uri}/connect/register
    oidc-user-info-uri: ${herodotus.endpoint.uaa-service-uri}/userinfo
  platform:
    architecture: distributed
    swagger:
      enabled: ${herodotus.switch.swagger.enabled}

server:
  shutdown: graceful
  jetty:
    connection-idle-timeout: 30000 #在请求延迟高时，避免线程被快速占满
  compression:
    enabled: true    # 启用GZIP压缩
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # 压缩类型
    min-response-size: 1024  # 最小压缩响应大小

spring:
  cloud:
    loadbalancer:
      nacos:
        enabled: true
  http:
    clients:
      imperative:
        factory: jdk
  web:
    error:
      include-exception: true
      include-message: always
      include-stacktrace: always
      include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS

springdoc:
  default-flat-param-object: true
  api-docs:
    enabled: ${herodotus.switch.swagger.enabled}
    resolve-schema-properties: true
  swagger-ui:
    enabled: ${herodotus.switch.swagger.enabled}
    disable-swagger-default-url: true
    operations-sorter: method
    show-common-extensions: true
    show-extensions: true
    oauth:
      use-pkce-with-authorization-code-grant: true
      app-name: ${spring.application.name}

sms:
  is-print: false