spring:
  data:
    redis:
      database: ${herodotus.environment.redis.database}
      host: ${herodotus.environment.redis.host}
      password: ${herodotus.environment.redis.password}
      port: ${herodotus.environment.redis.port}
      timeout: 3000ms
      lettuce:
        pool:
          enabled: true
          # 最大活跃连接数 (根据负载动态调整)。计算公式：max-active = (平均QPS × 平均耗时(秒)) / 可用实例数 + 缓冲值
          max-active: 64
          # 最大空闲连接数 (建议max-active的50-75%)。足够覆盖流量波谷，避免频繁创建连接
          max-idle: 32
          # 最小空闲连接数 (保持预热连接)。保持预热连接，应对突发流量
          min-idle: 8
          # 短等待避免线程阻塞，超时快速失败
          max-wait: 5000ms
          # 空闲连接检查间隔
          time-between-eviction-runs: 30s
        shutdown-timeout: 200ms
    redisson:
      enabled: false
      single-server-config:
        address: redis://${spring.data.redis.host}:${spring.data.redis.port}
#        password: ${spring.data.redis.password}

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson2
      limit: 10000
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson2
      broadcastChannel: herodotus
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: ${spring.data.redis.lettuce.pool.min-idle}
        maxIdle: ${spring.data.redis.lettuce.pool.max-idle}
        maxTotal: ${spring.data.redis.lettuce.pool.max-active}
        maxWait: ${spring.data.redis.lettuce.pool.max-wait}
      uri:
        - redis://${spring.data.redis.password}@${spring.data.redis.host}:${spring.data.redis.port}/${spring.data.redis.database}