herodotus:
  endpoint:
    uaa-service-name: dante-cloud-uaa
    upms-service-name: dante-cloud-upms
    message-service-name: dante-cloud-message
    oss-service-name: dante-cloud-oss-ability
    gateway-service-uri: ${herodotus.environment.gateway-server-addr}
    uaa-service-uri: ${herodotus.endpoint.gateway-service-uri}/${herodotus.endpoint.uaa-service-name}
    upms-service-uri: ${herodotus.endpoint.gateway-service-uri}/${herodotus.endpoint.upms-service-name}
    message-service-uri: ${herodotus.endpoint.gateway-service-uri}/${herodotus.endpoint.message-service-name}
    oss-service-uri: ${herodotus.endpoint.gateway-service-uri}/${herodotus.endpoint.oss-service-name}
    access-token-uri: ${herodotus.endpoint.uaa-service-uri}/oauth2/token
    authorization-uri: ${herodotus.endpoint.uaa-service-uri}/oauth2/authorize
    pushed-authorization-request-uri: ${herodotus.endpoint.uaa-service-uri}/oauth2/par
    token-revocation-uri: ${herodotus.endpoint.uaa-service-uri}/oauth2/revoke
    token-introspection-uri: ${herodotus.endpoint.uaa-service-uri}/oauth2/introspect
    jwk-set-uri: ${herodotus.endpoint.uaa-service-uri}/oauth2/jwks
    issuer-uri: ${herodotus.endpoint.uaa-service-uri}
    oidc-client-registration-uri: ${herodotus.endpoint.uaa-service-uri}/connect/register
    oidc-user-info-uri: ${herodotus.endpoint.uaa-service-uri}/userinfo
  oauth2:
    jwk:
      certificate: standard
  platform:
    architecture: distributed
    swagger:
      enabled: ${herodotus.switch.swagger.enabled}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

server:
  shutdown: graceful
  error:
    include-exception: true
    include-message: always
    include-stacktrace: always
    include-binding-errors: always
  servlet:
    session:
      timeout: ${herodotus.session.timeout}

spring:
  session:
    timeout: ${server.servlet.session.timeout}
    redis:
      repository-type: indexed
      flush-mode: immediate
  thymeleaf:
    mode: HTML
    cache: false

sms:
  is-print: false