herodotus:
  oauth2:
    jwk:
      certificate: standard

server:
  servlet:
    session:
      timeout: ${herodotus.session.timeout}

spring:
  threads:
    virtual:
      enabled: true
  session:
    timeout: ${server.servlet.session.timeout}
  thymeleaf:
    mode: HTML
    cache: false
  cloud:
    openfeign:
      http2client:
        enabled: true
      httpclient:
        enabled: false
        time-to-live: 15
        time-to-live-unit: seconds
        connection-timeout: 30000
        connection-timer-repeat: 3000
        max-connections: 500
        max-connections-per-route: 50
        hc5:
          connection-request-timeout: 15
          connection-request-timeout-unit: seconds
          socket-timeout: 15
          socket-timeout-unit: seconds
          pool-concurrency-policy: lax
          pool-reuse-policy: lifo
      compression:
        request:
          enabled: true
        response:
          enabled: true

feign:
  sentinel:
    enabled: true