spring:
  data:
    redis:
      database: ${herodotus.environment.redis.database}
      host: ${herodotus.environment.redis.host}
      password: ${herodotus.environment.redis.password}
      port: ${herodotus.environment.redis.port}
      timeout: 10000
      lettuce:
        pool:
          max-active: 10
          max-wait: 10000
          max-idle: 10
          min-idle: 5
    redisson:
      enabled: false
      single-server-config:
        address: redis://${spring.data.redis.host}:${spring.data.redis.port}
#        password: ${spring.data.redis.password}