services:
  upms:
    image: ${UPMS_SERVICE_NAME}:${VERSION}
    container_name: upms
    hostname: upms
    build:
      context: ../../../context
      dockerfile: production/Dockerfile
      args:
        - VERSION=${VERSION}
        - SERVICE_NAME=${UPMS_SERVICE_NAME}
        - SERVICE_PORT=${UPMS_SERVICE_PORT}
      platforms:
        - linux/amd64
        - linux/arm64
    environment:
      SW_AGENT_SERVICE_NAME: ${UPMS_SERVICE_NAME}
      SW_COLLECTOR_BACKEND_SERVICE: oap:11800
    ports:
      - ${UPMS_SERVICE_PORT}:${UPMS_SERVICE_PORT}
    volumes:
      - E:\\Workspaces\\docker-volumes\\dante-cloud\\logs:/usr/local/logs

  uaa:
    image: ${UAA_SERVICE_NAME}:${VERSION}
    container_name: uaa
    hostname: uaa
    build:
      context: ../../../context
      dockerfile: production/Dockerfile
      args:
        - VERSION=${VERSION}
        - SERVICE_NAME=${UAA_SERVICE_NAME}
        - SERVICE_PORT=${UAA_SERVICE_PORT}
      platforms:
        - linux/amd64
        - linux/arm64
    environment:
      SW_AGENT_SERVICE_NAME: ${UAA_SERVICE_NAME}
      SW_COLLECTOR_BACKEND_SERVICE: oap:11800
    ports:
      - ${UAA_SERVICE_PORT}:${UAA_SERVICE_PORT}
    volumes:
      - E:\\Workspaces\\docker-volumes\\dante-cloud\\logs:/usr/local/logs
    depends_on:
      - upms

  msg:
    image: ${MESSAGE_SERVICE_NAME}:${VERSION}
    container_name: msg
    hostname: msg
    build:
      context: ../../../context
      dockerfile: production/Dockerfile
      args:
        - VERSION=${VERSION}
        - SERVICE_NAME=${MESSAGE_SERVICE_NAME}
        - SERVICE_PORT=${MESSAGE_SERVICE_PORT}
      platforms:
        - linux/amd64
        - linux/arm64
    environment:
      SW_AGENT_SERVICE_NAME: ${MESSAGE_SERVICE_NAME}
      SW_COLLECTOR_BACKEND_SERVICE: oap:11800
    ports:
      - ${MESSAGE_SERVICE_PORT}:${MESSAGE_SERVICE_PORT}
    depends_on:
      - uaa

  oss:
    image: ${OSS_SERVICE_NAME}:${VERSION}
    container_name: oss
    hostname: oss
    build:
      context: ../../../context
      dockerfile: production/Dockerfile
      args:
        - VERSION=${VERSION}
        - SERVICE_NAME=${OSS_SERVICE_NAME}
        - SERVICE_PORT=${OSS_SERVICE_PORT}
      platforms:
        - linux/amd64
        - linux/arm64
    environment:
      SW_AGENT_SERVICE_NAME: ${OSS_SERVICE_NAME}
      SW_COLLECTOR_BACKEND_SERVICE: oap:11800
    ports:
      - ${OSS_SERVICE_PORT}:${OSS_SERVICE_PORT}
    volumes:
      - E:\\Workspaces\\docker-volumes\\dante-cloud\\logs:/usr/local/logs
    depends_on:
      - msg

  gateway:
    image: ${GATEWAY_SERVICE_NAME}:${VERSION}
    container_name: gateway
    hostname: gateway
    build:
      context: ../../../context
      dockerfile: production/Dockerfile
      args:
        - VERSION=${VERSION}
        - SERVICE_NAME=${GATEWAY_SERVICE_NAME}
        - SERVICE_PORT=${GATEWAY_SERVICE_PORT}
      platforms:
        - linux/amd64
        - linux/arm64
    environment:
      SW_AGENT_SERVICE_NAME: ${GATEWAY_SERVICE_NAME}
      SW_COLLECTOR_BACKEND_SERVICE: oap:11800
    ports:
      - ${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}
    volumes:
      - E:\\Workspaces\\docker-volumes\\dante-cloud\\logs:/usr/local/logs
    depends_on:
      - oss

  bpmn:
    image: ${BPMN_SERVICE_NAME}:${VERSION}
    container_name: bpmn
    hostname: bpmn
    build:
      context: ../../../context
      dockerfile: production/Dockerfile
      args:
        - VERSION=${VERSION}
        - SERVICE_NAME=${BPMN_SERVICE_NAME}
        - SERVICE_PORT=${BPMN_SERVICE_PORT}
      platforms:
        - linux/amd64
        - linux/arm64
    environment:
      SW_AGENT_SERVICE_NAME: ${BPMN_SERVICE_NAME}
      SW_COLLECTOR_BACKEND_SERVICE: oap:11800
    ports:
      - ${BPMN_SERVICE_PORT}:${BPMN_SERVICE_PORT}
    volumes:
      - E:\\Workspaces\\docker-volumes\\dante-cloud\\logs:/usr/local/logs
    depends_on:
      - gateway

  monitor:
    image: ${MONITOR_SERVICE_NAME}:${VERSION}
    container_name: monitor
    hostname: monitor
    build:
      context: ../../../context
      dockerfile: production/Dockerfile-Monitor
      args:
        - VERSION=${VERSION}
        - SERVICE_NAME=${MONITOR_SERVICE_NAME}
        - SERVICE_PORT=${MONITOR_SERVICE_PORT}
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - ${MONITOR_SERVICE_PORT}:${MONITOR_SERVICE_PORT}
    volumes:
      - E:\\Workspaces\\docker-volumes\\dante-cloud\\logs:/usr/local/logs
    depends_on:
      - gateway