/*
 Navicat Premium Dump SQL

 Source Server         : LOCAL_NACOS_PG
 Source Server Type    : PostgreSQL
 Source Server Version : 170002 (170002)
 Source Host           : 192.168.101.10:15432
 Source Catalog        : nacos
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 170002 (170002)
 File Encoding         : 65001

 Date: 26/05/2025 20:45:21
*/


-- ----------------------------
-- Sequence structure for config_info_aggr_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."config_info_aggr_id_seq";
CREATE SEQUENCE "public"."config_info_aggr_id_seq"
    INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for config_info_beta_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."config_info_beta_id_seq";
CREATE SEQUENCE "public"."config_info_beta_id_seq"
    INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for config_info_gray_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."config_info_gray_id_seq";
CREATE SEQUENCE "public"."config_info_gray_id_seq"
    INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for config_info_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."config_info_id_seq";
CREATE SEQUENCE "public"."config_info_id_seq"
    INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for config_info_tag_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."config_info_tag_id_seq";
CREATE SEQUENCE "public"."config_info_tag_id_seq"
    INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for config_tags_relation_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."config_tags_relation_id_seq";
CREATE SEQUENCE "public"."config_tags_relation_id_seq"
    INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for config_tags_relation_nid_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."config_tags_relation_nid_seq";
CREATE SEQUENCE "public"."config_tags_relation_nid_seq"
    INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for group_capacity_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."group_capacity_id_seq";
CREATE SEQUENCE "public"."group_capacity_id_seq"
    INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for his_config_info_nid_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."his_config_info_nid_seq";
CREATE SEQUENCE "public"."his_config_info_nid_seq"
    INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for tenant_capacity_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."tenant_capacity_id_seq";
CREATE SEQUENCE "public"."tenant_capacity_id_seq"
    INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;


-- ----------------------------
-- Sequence structure for tenant_info_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."tenant_info_id_seq";
CREATE SEQUENCE "public"."tenant_info_id_seq"
    INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for config_info
-- ----------------------------
DROP TABLE IF EXISTS "public"."config_info";
CREATE TABLE "public"."config_info" (
                                        "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                            INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
                                        "data_id" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
                                        "group_id" varchar(128) COLLATE "pg_catalog"."default",
                                        "content" text COLLATE "pg_catalog"."default" NOT NULL,
                                        "md5" varchar(32) COLLATE "pg_catalog"."default",
                                        "gmt_create" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                        "gmt_modified" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                        "src_user" text COLLATE "pg_catalog"."default",
                                        "src_ip" varchar(50) COLLATE "pg_catalog"."default",
                                        "app_name" varchar(128) COLLATE "pg_catalog"."default",
                                        "tenant_id" varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
                                        "c_desc" varchar(256) COLLATE "pg_catalog"."default",
                                        "c_use" varchar(64) COLLATE "pg_catalog"."default",
                                        "effect" varchar(64) COLLATE "pg_catalog"."default",
                                        "type" varchar(64) COLLATE "pg_catalog"."default",
                                        "c_schema" text COLLATE "pg_catalog"."default",
                                        "encrypted_data_key" varchar(1024) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying
)
;
COMMENT ON COLUMN "public"."config_info"."id" IS 'id';
COMMENT ON COLUMN "public"."config_info"."data_id" IS 'data_id';
COMMENT ON COLUMN "public"."config_info"."group_id" IS 'group_id';
COMMENT ON COLUMN "public"."config_info"."content" IS 'content';
COMMENT ON COLUMN "public"."config_info"."md5" IS 'md5';
COMMENT ON COLUMN "public"."config_info"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."config_info"."gmt_modified" IS '修改时间';
COMMENT ON COLUMN "public"."config_info"."src_user" IS 'source user';
COMMENT ON COLUMN "public"."config_info"."src_ip" IS 'source ip';
COMMENT ON COLUMN "public"."config_info"."app_name" IS 'app_name';
COMMENT ON COLUMN "public"."config_info"."tenant_id" IS '租户字段';
COMMENT ON COLUMN "public"."config_info"."c_desc" IS 'configuration description';
COMMENT ON COLUMN "public"."config_info"."c_use" IS 'configuration usage';
COMMENT ON COLUMN "public"."config_info"."effect" IS '配置生效的描述';
COMMENT ON COLUMN "public"."config_info"."type" IS '配置的类型';
COMMENT ON COLUMN "public"."config_info"."c_schema" IS '配置的模式';
COMMENT ON COLUMN "public"."config_info"."encrypted_data_key" IS '密钥';
COMMENT ON TABLE "public"."config_info" IS 'config_info';

-- ----------------------------
-- Table structure for config_info_beta
-- ----------------------------
DROP TABLE IF EXISTS "public"."config_info_beta";
CREATE TABLE "public"."config_info_beta" (
                                             "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                 INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
                                             "data_id" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
                                             "group_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
                                             "app_name" varchar(128) COLLATE "pg_catalog"."default",
                                             "content" text COLLATE "pg_catalog"."default" NOT NULL,
                                             "beta_ips" varchar(1024) COLLATE "pg_catalog"."default",
                                             "md5" varchar(32) COLLATE "pg_catalog"."default",
                                             "gmt_create" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                             "gmt_modified" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                             "src_user" text COLLATE "pg_catalog"."default",
                                             "src_ip" varchar(50) COLLATE "pg_catalog"."default",
                                             "tenant_id" varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
                                             "encrypted_data_key" varchar(1024) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying
)
;
COMMENT ON COLUMN "public"."config_info_beta"."id" IS 'id';
COMMENT ON COLUMN "public"."config_info_beta"."data_id" IS 'data_id';
COMMENT ON COLUMN "public"."config_info_beta"."group_id" IS 'group_id';
COMMENT ON COLUMN "public"."config_info_beta"."app_name" IS 'app_name';
COMMENT ON COLUMN "public"."config_info_beta"."content" IS 'content';
COMMENT ON COLUMN "public"."config_info_beta"."beta_ips" IS 'betaIps';
COMMENT ON COLUMN "public"."config_info_beta"."md5" IS 'md5';
COMMENT ON COLUMN "public"."config_info_beta"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."config_info_beta"."gmt_modified" IS '修改时间';
COMMENT ON COLUMN "public"."config_info_beta"."src_user" IS 'source user';
COMMENT ON COLUMN "public"."config_info_beta"."src_ip" IS 'source ip';
COMMENT ON COLUMN "public"."config_info_beta"."tenant_id" IS '租户字段';
COMMENT ON COLUMN "public"."config_info_beta"."encrypted_data_key" IS '密钥';
COMMENT ON TABLE "public"."config_info_beta" IS 'config_info_beta';

-- ----------------------------
-- Table structure for config_info_gray
-- ----------------------------
DROP TABLE IF EXISTS "public"."config_info_gray";
CREATE TABLE "public"."config_info_gray" (
                                             "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                 INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
                                             "data_id" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
                                             "group_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
                                             "content" text COLLATE "pg_catalog"."default" NOT NULL,
                                             "md5" varchar(32) COLLATE "pg_catalog"."default",
                                             "src_user" text COLLATE "pg_catalog"."default",
                                             "src_ip" varchar(100) COLLATE "pg_catalog"."default",
                                             "gmt_create" timestamp(3) NOT NULL,
                                             "gmt_modified" timestamp(3) NOT NULL,
                                             "app_name" varchar(128) COLLATE "pg_catalog"."default",
                                             "tenant_id" varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
                                             "gray_name" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
                                             "gray_rule" text COLLATE "pg_catalog"."default" NOT NULL,
                                             "encrypted_data_key" varchar(256) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying
)
;
COMMENT ON COLUMN "public"."config_info_gray"."id" IS 'id';
COMMENT ON COLUMN "public"."config_info_gray"."data_id" IS 'data_id';
COMMENT ON COLUMN "public"."config_info_gray"."group_id" IS 'group_id';
COMMENT ON COLUMN "public"."config_info_gray"."content" IS 'content';
COMMENT ON COLUMN "public"."config_info_gray"."md5" IS 'md5';
COMMENT ON COLUMN "public"."config_info_gray"."src_user" IS 'src_user';
COMMENT ON COLUMN "public"."config_info_gray"."src_ip" IS 'src_ip';
COMMENT ON COLUMN "public"."config_info_gray"."gmt_create" IS 'gmt_create';
COMMENT ON COLUMN "public"."config_info_gray"."gmt_modified" IS 'gmt_modified';
COMMENT ON COLUMN "public"."config_info_gray"."app_name" IS 'app_name';
COMMENT ON COLUMN "public"."config_info_gray"."tenant_id" IS 'tenant_id';
COMMENT ON COLUMN "public"."config_info_gray"."gray_name" IS 'gray_name';
COMMENT ON COLUMN "public"."config_info_gray"."gray_rule" IS 'gray_rule';
COMMENT ON COLUMN "public"."config_info_gray"."encrypted_data_key" IS 'encrypted_data_key';
COMMENT ON TABLE "public"."config_info_gray" IS 'config_info_gray';

-- ----------------------------
-- Table structure for config_info_tag
-- ----------------------------
DROP TABLE IF EXISTS "public"."config_info_tag";
CREATE TABLE "public"."config_info_tag" (
                                            "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
                                            "data_id" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
                                            "group_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
                                            "tenant_id" varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
                                            "tag_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
                                            "app_name" varchar(128) COLLATE "pg_catalog"."default",
                                            "content" text COLLATE "pg_catalog"."default" NOT NULL,
                                            "md5" varchar(32) COLLATE "pg_catalog"."default",
                                            "gmt_create" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                            "gmt_modified" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                            "src_user" text COLLATE "pg_catalog"."default",
                                            "src_ip" varchar(50) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "public"."config_info_tag"."id" IS 'id';
COMMENT ON COLUMN "public"."config_info_tag"."data_id" IS 'data_id';
COMMENT ON COLUMN "public"."config_info_tag"."group_id" IS 'group_id';
COMMENT ON COLUMN "public"."config_info_tag"."tenant_id" IS 'tenant_id';
COMMENT ON COLUMN "public"."config_info_tag"."tag_id" IS 'tag_id';
COMMENT ON COLUMN "public"."config_info_tag"."app_name" IS 'app_name';
COMMENT ON COLUMN "public"."config_info_tag"."content" IS 'content';
COMMENT ON COLUMN "public"."config_info_tag"."md5" IS 'md5';
COMMENT ON COLUMN "public"."config_info_tag"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."config_info_tag"."gmt_modified" IS '修改时间';
COMMENT ON COLUMN "public"."config_info_tag"."src_user" IS 'source user';
COMMENT ON COLUMN "public"."config_info_tag"."src_ip" IS 'source ip';
COMMENT ON TABLE "public"."config_info_tag" IS 'config_info_tag';

-- ----------------------------
-- Table structure for config_tags_relation
-- ----------------------------
DROP TABLE IF EXISTS "public"."config_tags_relation";
CREATE TABLE "public"."config_tags_relation" (
                                                 "id" int8 NOT NULL,
                                                 "tag_name" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
                                                 "tag_type" varchar(64) COLLATE "pg_catalog"."default",
                                                 "data_id" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
                                                 "group_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
                                                 "tenant_id" varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
                                                 "nid" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                     INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
)
)
;
COMMENT ON COLUMN "public"."config_tags_relation"."id" IS 'id';
COMMENT ON COLUMN "public"."config_tags_relation"."tag_name" IS 'tag_name';
COMMENT ON COLUMN "public"."config_tags_relation"."tag_type" IS 'tag_type';
COMMENT ON COLUMN "public"."config_tags_relation"."data_id" IS 'data_id';
COMMENT ON COLUMN "public"."config_tags_relation"."group_id" IS 'group_id';
COMMENT ON COLUMN "public"."config_tags_relation"."tenant_id" IS 'tenant_id';
COMMENT ON COLUMN "public"."config_tags_relation"."nid" IS 'nid, 自增长标识';
COMMENT ON TABLE "public"."config_tags_relation" IS 'config_tag_relation';

-- ----------------------------
-- Table structure for group_capacity
-- ----------------------------
DROP TABLE IF EXISTS "public"."group_capacity";
CREATE TABLE "public"."group_capacity" (
                                           "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                               INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
                                           "group_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
                                           "quota" int8 NOT NULL DEFAULT 0,
                                           "usage" int8 NOT NULL DEFAULT 0,
                                           "max_size" int8 NOT NULL DEFAULT 0,
                                           "max_aggr_count" int8 NOT NULL DEFAULT 0,
                                           "max_aggr_size" int8 NOT NULL DEFAULT 0,
                                           "max_history_count" int8 NOT NULL DEFAULT 0,
                                           "gmt_create" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                           "gmt_modified" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
)
;
COMMENT ON COLUMN "public"."group_capacity"."id" IS '主键ID';
COMMENT ON COLUMN "public"."group_capacity"."group_id" IS 'Group ID，空字符表示整个集群';
COMMENT ON COLUMN "public"."group_capacity"."quota" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "public"."group_capacity"."usage" IS '使用量';
COMMENT ON COLUMN "public"."group_capacity"."max_size" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "public"."group_capacity"."max_aggr_count" IS '聚合子配置最大个数，，0表示使用默认值';
COMMENT ON COLUMN "public"."group_capacity"."max_aggr_size" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "public"."group_capacity"."max_history_count" IS '最大变更历史数量';
COMMENT ON COLUMN "public"."group_capacity"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."group_capacity"."gmt_modified" IS '修改时间';
COMMENT ON TABLE "public"."group_capacity" IS '集群、各Group容量信息表';

-- ----------------------------
-- Table structure for his_config_info
-- ----------------------------
DROP TABLE IF EXISTS "public"."his_config_info";
CREATE TABLE "public"."his_config_info" (
                                            "id" int8 NOT NULL,
                                            "nid" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
                                            "data_id" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
                                            "group_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
                                            "app_name" varchar(128) COLLATE "pg_catalog"."default",
                                            "content" text COLLATE "pg_catalog"."default" NOT NULL,
                                            "md5" varchar(32) COLLATE "pg_catalog"."default",
                                            "gmt_create" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                            "gmt_modified" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                            "src_user" text COLLATE "pg_catalog"."default",
                                            "src_ip" varchar(50) COLLATE "pg_catalog"."default",
                                            "op_type" char(10) COLLATE "pg_catalog"."default",
                                            "tenant_id" varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
                                            "gray_name" varchar(50) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
                                            "encrypted_data_key" varchar(1024) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
                                            "publish_type" varchar(50) COLLATE "pg_catalog"."default" DEFAULT 'formal'::character varying,
                                            "ext_info" text COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "public"."his_config_info"."id" IS 'id';
COMMENT ON COLUMN "public"."his_config_info"."nid" IS 'nid, 自增标识';
COMMENT ON COLUMN "public"."his_config_info"."data_id" IS 'data_id';
COMMENT ON COLUMN "public"."his_config_info"."group_id" IS 'group_id';
COMMENT ON COLUMN "public"."his_config_info"."app_name" IS 'app_name';
COMMENT ON COLUMN "public"."his_config_info"."content" IS 'content';
COMMENT ON COLUMN "public"."his_config_info"."md5" IS 'md5';
COMMENT ON COLUMN "public"."his_config_info"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."his_config_info"."gmt_modified" IS '修改时间';
COMMENT ON COLUMN "public"."his_config_info"."src_user" IS 'source user';
COMMENT ON COLUMN "public"."his_config_info"."src_ip" IS 'source ip';
COMMENT ON COLUMN "public"."his_config_info"."op_type" IS 'operation type';
COMMENT ON COLUMN "public"."his_config_info"."tenant_id" IS '租户字段';
COMMENT ON COLUMN "public"."his_config_info"."gray_name" IS 'gray_name';
COMMENT ON COLUMN "public"."his_config_info"."encrypted_data_key" IS '密钥';
COMMENT ON COLUMN "public"."his_config_info"."publish_type" IS 'publish type gray or formal';
COMMENT ON COLUMN "public"."his_config_info"."ext_info" IS 'ext info';
COMMENT ON TABLE "public"."his_config_info" IS '多租户改造';

-- ----------------------------
-- Table structure for permissions
-- ----------------------------
DROP TABLE IF EXISTS "public"."permissions";
CREATE TABLE "public"."permissions" (
                                        "role" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
                                        "resource" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
                                        "action" varchar(8) COLLATE "pg_catalog"."default" NOT NULL
)
;
COMMENT ON COLUMN "public"."permissions"."role" IS 'role';
COMMENT ON COLUMN "public"."permissions"."resource" IS 'resource';
COMMENT ON COLUMN "public"."permissions"."action" IS 'action';

-- ----------------------------
-- Table structure for roles
-- ----------------------------
DROP TABLE IF EXISTS "public"."roles";
CREATE TABLE "public"."roles" (
                                  "username" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
                                  "role" varchar(50) COLLATE "pg_catalog"."default" NOT NULL
)
;
COMMENT ON COLUMN "public"."roles"."username" IS 'username';
COMMENT ON COLUMN "public"."roles"."role" IS 'role';

-- ----------------------------
-- Table structure for tenant_capacity
-- ----------------------------
DROP TABLE IF EXISTS "public"."tenant_capacity";
CREATE TABLE "public"."tenant_capacity" (
                                            "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
                                            "tenant_id" varchar(128) COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::character varying,
                                            "quota" int8 NOT NULL DEFAULT 0,
                                            "usage" int8 NOT NULL DEFAULT 0,
                                            "max_size" int8 NOT NULL DEFAULT 0,
                                            "max_aggr_count" int8 NOT NULL DEFAULT 0,
                                            "max_aggr_size" int8 NOT NULL DEFAULT 0,
                                            "max_history_count" int8 NOT NULL DEFAULT 0,
                                            "gmt_create" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                            "gmt_modified" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
)
;
COMMENT ON COLUMN "public"."tenant_capacity"."id" IS '主键ID';
COMMENT ON COLUMN "public"."tenant_capacity"."tenant_id" IS 'Tenant ID';
COMMENT ON COLUMN "public"."tenant_capacity"."quota" IS '配额，0表示使用默认值';
COMMENT ON COLUMN "public"."tenant_capacity"."usage" IS '使用量';
COMMENT ON COLUMN "public"."tenant_capacity"."max_size" IS '单个配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "public"."tenant_capacity"."max_aggr_count" IS '聚合子配置最大个数';
COMMENT ON COLUMN "public"."tenant_capacity"."max_aggr_size" IS '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值';
COMMENT ON COLUMN "public"."tenant_capacity"."max_history_count" IS '最大变更历史数量';
COMMENT ON COLUMN "public"."tenant_capacity"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."tenant_capacity"."gmt_modified" IS '修改时间';
COMMENT ON TABLE "public"."tenant_capacity" IS '租户容量信息表';

-- ----------------------------
-- Table structure for tenant_info
-- ----------------------------
DROP TABLE IF EXISTS "public"."tenant_info";
CREATE TABLE "public"."tenant_info" (
                                        "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                            INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
                                        "kp" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
                                        "tenant_id" varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
                                        "tenant_name" varchar(128) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
                                        "tenant_desc" varchar(256) COLLATE "pg_catalog"."default",
                                        "create_source" varchar(32) COLLATE "pg_catalog"."default",
                                        "gmt_create" int8 NOT NULL,
                                        "gmt_modified" int8 NOT NULL
)
;
COMMENT ON COLUMN "public"."tenant_info"."id" IS 'id';
COMMENT ON COLUMN "public"."tenant_info"."kp" IS 'kp';
COMMENT ON COLUMN "public"."tenant_info"."tenant_id" IS 'tenant_id';
COMMENT ON COLUMN "public"."tenant_info"."tenant_name" IS 'tenant_name';
COMMENT ON COLUMN "public"."tenant_info"."tenant_desc" IS 'tenant_desc';
COMMENT ON COLUMN "public"."tenant_info"."create_source" IS 'create_source';
COMMENT ON COLUMN "public"."tenant_info"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."tenant_info"."gmt_modified" IS '修改时间';
COMMENT ON TABLE "public"."tenant_info" IS 'tenant_info';

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS "public"."users";
CREATE TABLE "public"."users" (
                                  "username" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
                                  "password" varchar(500) COLLATE "pg_catalog"."default" NOT NULL,
                                  "enabled" bool NOT NULL
)
;
COMMENT ON COLUMN "public"."users"."username" IS 'username';
COMMENT ON COLUMN "public"."users"."password" IS 'password';
COMMENT ON COLUMN "public"."users"."enabled" IS 'enabled';

-- ----------------------------
-- Indexes structure for table config_info
-- ----------------------------
CREATE UNIQUE INDEX "config_info_data_id_group_id_tenant_id_idx" ON "public"."config_info" USING btree (
    "data_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
    "group_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
    "tenant_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
    );

-- ----------------------------
-- Indexes structure for table config_info_beta
-- ----------------------------
CREATE UNIQUE INDEX "config_info_beta_data_id_group_id_tenant_id_idx" ON "public"."config_info_beta" USING btree (
    "data_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
    "group_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
    "tenant_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
    );

-- ----------------------------
-- Indexes structure for table config_info_gray
-- ----------------------------
CREATE INDEX "config_info_gray_data_id_gmt_modified_idx" ON "public"."config_info_gray" USING btree (
    "data_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
    "gmt_modified" "pg_catalog"."timestamp_ops" ASC NULLS LAST
    );
CREATE UNIQUE INDEX "config_info_gray_data_id_group_id_tenant_id_gray_name_idx" ON "public"."config_info_gray" USING btree (
    "data_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
    "group_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
    "tenant_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
    "gray_name" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
    );
CREATE INDEX "config_info_gray_gmt_modified_idx" ON "public"."config_info_gray" USING btree (
    "gmt_modified" "pg_catalog"."timestamp_ops" ASC NULLS LAST
    );

-- ----------------------------
-- Indexes structure for table config_info_tag
-- ----------------------------
CREATE UNIQUE INDEX "config_info_tag_data_id_group_id_tenant_id_tag_id_idx" ON "public"."config_info_tag" USING btree (
    "data_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
    "group_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
    "tenant_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
    "tag_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
    );

-- ----------------------------
-- Indexes structure for table config_tags_relation
-- ----------------------------
CREATE UNIQUE INDEX "config_tags_relation_id_tag_name_tag_type_idx" ON "public"."config_tags_relation" USING btree (
    "id" "pg_catalog"."int8_ops" ASC NULLS LAST,
    "tag_name" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
    "tag_type" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
    );
CREATE INDEX "config_tags_relation_tenant_id_idx" ON "public"."config_tags_relation" USING btree (
    "tenant_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
    );

-- ----------------------------
-- Indexes structure for table group_capacity
-- ----------------------------
CREATE UNIQUE INDEX "group_capacity_group_id_idx" ON "public"."group_capacity" USING btree (
    "group_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
    );

-- ----------------------------
-- Indexes structure for table his_config_info
-- ----------------------------
CREATE INDEX "his_config_info_data_id_idx" ON "public"."his_config_info" USING btree (
    "data_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
    );
CREATE INDEX "his_config_info_gmt_create_idx" ON "public"."his_config_info" USING btree (
    "gmt_create" "pg_catalog"."timestamp_ops" ASC NULLS LAST
    );
CREATE INDEX "his_config_info_gmt_modified_idx" ON "public"."his_config_info" USING btree (
    "gmt_modified" "pg_catalog"."timestamp_ops" ASC NULLS LAST
    );

-- ----------------------------
-- Indexes structure for table permissions
-- ----------------------------
CREATE UNIQUE INDEX "permissions_role_resource_action_idx" ON "public"."permissions" USING btree (
    "role" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
    "resource" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
    "action" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
    );

-- ----------------------------
-- Indexes structure for table roles
-- ----------------------------
CREATE UNIQUE INDEX "roles_username_role_idx" ON "public"."roles" USING btree (
    "username" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
    "role" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
    );

-- ----------------------------
-- Indexes structure for table tenant_capacity
-- ----------------------------
CREATE UNIQUE INDEX "tenant_capacity_tenant_id_idx" ON "public"."tenant_capacity" USING btree (
    "tenant_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
    );

-- ----------------------------
-- Indexes structure for table tenant_info
-- ----------------------------
CREATE UNIQUE INDEX "tenant_info_kp_tenant_id_idx" ON "public"."tenant_info" USING btree (
    "kp" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
    "tenant_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
    );
CREATE INDEX "tenant_info_tenant_id_idx" ON "public"."tenant_info" USING btree (
    "tenant_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
    );
