server:
  port: 8846
spring:
  application:
    name: @artifactId@ #拿到POM文件中的值
  profiles:
    active: @facility@

---
# spring cloud alibaba 基础设施配置
spring:
  config:
    activate:
      on-profile: alibaba
    import:
      - nacos:dante-cloud-environment.yaml?group=${PROFILE:@profile@}
      - nacos:dante-cloud-platform.yaml?group=common
      - nacos:dante-cloud-database-${DATABASE:@database@}.yaml?group=common
      - nacos:dante-cloud-database.yaml?group=common
      - nacos:dante-cloud-redis.yaml?group=common
      - nacos:dante-cloud-cache.yaml?group=common
      - nacos:dante-cloud-rest.yaml?group=common
      - nacos:dante-cloud-kafka.yaml?group=common
      # 本地存储模式必须要包含
      # 远程存储：social 配置在 upms
      # 本地存储：social 配置在 uaa
      - nacos:dante-cloud-social.yaml?group=common
      - nacos:${spring.application.name}.yaml?group=service
  cloud:
    nacos:
      username: ${ALIBABA_USERNAME:@alibaba.username@}
      password: ${ALIBABA_PASSWORD:@alibaba.password@}
      config:
        namespace: ${ALIBABA_NAMESPACE:@alibaba.namespace@}
        server-addr: ${ALIBABA_CONFIG_SERVER_ADDR:@alibaba.config.server-addr@}
        file-extension: yaml
      discovery:
        namespace: ${ALIBABA_NAMESPACE:@alibaba.namespace@}
        server-addr: ${ALIBABA_DISCOVERY_SERVER_ADDR:@alibaba.discovery.server-addr@}
    sentinel:
      eager: true
      transport:
        port: 8719
        dashboard: ${ALIBABA_SENTINEL_SERVER_ADDR:@alibaba.sentinel.server-addr@}
    #      datasource:
    #        flow:
    #          nacos:
    #            server-addr: @alibaba.config.server-addr@
    #            data-id: ${spring.application.name}-sentienl-flow.json
    #            group-id: management
    #            data-type: json
    #            rule-type: flow


logging:
  file:
    name: logs/${spring.application.name}.log
  #  config: http://${spring.cloud.nacos.config.server-addr}/nacos/v1/cs/configs?group=logs&tenant=${spring.cloud.nacos.config.namespace}&dataId=logback-spring.xml
  #  config: http://${spring.cloud.nacos.config.server-addr}/nacos/v1/cs/configs?group=logs&dataId=logback-spring.xml
  level:
    root: INFO
    # 关闭不必要的日志
    org.reflections.Reflections: off
    com.alibaba.nacos.client: error
    com.alibaba.nacos.common.remote.client: error
    com.ulisesbocchio: error
    # 开发、调试需要的日志
    cn.herodotus: debug
    org.springframework.security: info
    org.springframework.web: info
    com.alicp.jetcache: trace
    org.springframework.cloud.bus: info
    org.apache.kafka: warn

---
# spring cloud tencent 基础设施配置
spring:
  config:
    activate:
      on-profile: tencent
  cloud:
#    inetutils:
#      ignored-interfaces:
#        - eth0
    polaris:
      enabled: true
      address: ${TENCENT_POLARIS_SERVER_ADDR:grpc://@tencent.polaris.server-addr@}
      namespace: ${TENCENT_POLARIS_NAMESPACE:@tencent.polaris.namespace@}
      config:
        address: ${TENCENT_POLARIS_CONFIG_ADDR:grpc://@tencent.polaris.config-addr@}
        data-source: ${TENCENT_POLARIS_DATA_SOURCE:@tencent.polaris.data.source@}
        local-file-root-path: ${TENCENT_POLARIS_LOCAL_DIR:@tencent.polaris.local.dir@}
        groups:
          - name: ${PROFILE:@profile@}
            files:
              - dante-cloud-environment.yaml
          - name: common
            files:
              - dante-cloud-platform.yaml
              - dante-cloud-database-${DATABASE:@database@}.yaml
              - dante-cloud-database.yaml
              - dante-cloud-redis.yaml
              - dante-cloud-cache.yaml
              - dante-cloud-rest.yaml
              - dante-cloud-kafka.yaml
              - dante-cloud-social.yaml
          - name: service
            files:
              - ${spring.application.name}.yaml

logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    root: INFO
    # 开发、调试需要的日志
    org.springframework.security: info
    org.springframework.web: debug
    org.springframework.cloud.bus: info
    org.apache.kafka: warn
    cn.herodotus: info
---
# spring 全家桶基础设施配置
spring:
  config:
    activate:
      on-profile: spring
  cloud:
    inetutils:
      ignored-interfaces:
        - eth0
    zookeeper:
      discovery:
        instance-host: ${spring.cloud.client.ip-address}